export const CATEGORIES = {
  olympiad: "Олимпиада",
  mun: "Модель ООН",
  conference: "Конференция",
  volunteering: "Волонтёрство",
  internship: "Стажировка",
  courses: "Курсы",
  film_meetup: "Киновстреча",
  book_club: "Книжный клуб",
  english_talking_club: "English Talking Club",
  contest: "Конкурс",
  training: "Тренинг",
  seminar: "Семинар",
  workshop: "Мастерская",
  hackathon: "Хакатон",
  lecture: "Лекция",
  debate: "Дебаты",
  career_fair: "Карьерная ярмарка",
  scholarship: "Стипендия",
  exhibition: "Выставка",
  other: "Другое",
};
